removed redundant messages and fix bugs
moshekan/TennisTelegramBot pull request #3
Opened 2021-09-03 22:21 UTC by mayaraz

- removed redundant messages every 10 minutes
- added log to `run_job` function
- fix two weeks bug (?)

2021-09-03 22:23 UTC, mayaraz commented on bot.py
> +        if (job.context.time - datetime.now()).days > timedelta(weeks=2).days:
Is this fixes the bug?
@moshekan

2021-09-06 15:49 UTC, moshekan commented on bot.py
> +        if (job.context.time - datetime.now()).days > timedelta(weeks=2).days:
Seems like it

2021-09-06 15:56 UTC, moshekan requested changes

2021-09-06 15:56 UTC, moshekan commented on bot.py
> +        if job.context.time - timedelta(hours=3) < (datetime.now()):
I know that you haven't touched it, but worth reducing to 1 hour

2021-09-06 15:56 UTC, moshekan commented on bot.py
> +        logger.info(f"Job: {job.name}\n Could not find a court will try again in 10 minutes.")
Didn't you remove it?

2021-09-06 19:41 UTC, mayaraz commented on bot.py
> +        logger.info(f"Job: {job.name}\n Could not find a court will try again in 10 minutes.")
I log it now, instead of sending it

2021-09-07 13:24 UTC, merged